spring.application.name=vehicle-registration-system

spring.profiles.default=dev

spring.config.import=optional:file:./config/application-local.properties

spring.jpa.open-in-view=false

management.endpoints.web.exposure.include=health,info
server.error.include-message=never

vrs.registration.validity-years=15


