spring.datasource.url=jdbc:mysql://localhost:3306/nexturn26
spring.datasource.username=root
DB_PASSWORD=Ssadh12345@
vrs.seed-demo=false
JWT_SECRET=0hiD5eIpKj01cpyVukU1vSY3QS9Iyma_0nCxaQ8BovI343OxPJN4ets6m4IwzPaa
